import os

lines = []
lines.append('"""')
lines.append('Asynchronous worker queue for facts extraction.')
lines.append('Reads player messages from an internal queue and processes them in a daemon thread')
lines.append('so the synchronous reply path is never blocked.')
lines.append('"""')
lines.append('import logging')
lines.append('import threading')
lines.append('import time')
lines.append('from collections import deque')
lines.append('from datetime import datetime, timezone')
lines.append('from typing import Optional')
lines.append('')
lines.append('logger = logging.getLogger("chief_ai_service.worker")')
lines.append('')
lines.append('')
lines.append('def _ts_utc() -> str:')
lines.append('    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")')
lines.append('')
lines.append('')
lines.append('class FactsWorker:')
lines.append('    """Daemon-thread worker that drains a queue of player messages for facts analysis."""')
lines.append('')
lines.append('    def __init__(self, max_retries: int = 3, maxlen: int = 100) -> None:')
lines.append('        self._queue: deque = deque(maxlen=maxlen)')
lines.append('        self._max_retries = max_retries')
lines.append('        self._lock = threading.Lock()')
lines.append('        self._thread: Optional[threading.Thread] = None')
lines.append('        self._running = False')
lines.append('')
lines.append('    def start(self) -> None:')
lines.append('        """Ensure the worker thread is running (idempotent)."""')
lines.append('        with self._lock:')
lines.append('            if self._running:')
lines.append('                return')
lines.append('            self._running = True')
lines.append('            self._thread = threading.Thread(')
lines.append('                target=self._run_loop,')
lines.append('                daemon=True,')
lines.append('                name="facts-worker",')
lines.append('            )')
lines.append('            self._thread.start()')
lines.append('            logger.info("FactsWorker started ts=%s max_retries=%d", _ts_utc(), self._max_retries)')
lines.append('')
lines.append('    def stop(self) -> None:')
lines.append('        """Gracefully ask the worker to stop (best-effort)."""')
lines.append('        with self._lock:')
lines.append('            self._running = False')
lines.append('        logger.info("FactsWorker stop requested ts=%s", _ts_utc())')
lines.append('')
lines.append('    def enqueue(self, player_uuid: str, chief_name: str, player_message: str) -> None:')
lines.append('        """Drop a message into the worker queue. Never blocks.')
lines.append('')
lines.append('        If the queue is full the oldest entry is silently discarded (deque maxlen).')
lines.append('        """')
lines.append('        entry = {')
lines.append('            "player_uuid": player_uuid,')
lines.append('            "chief_name": chief_name,')
lines.append('            "player_message": player_message,')
lines.append('            "retries": 0,')
lines.append('        }')
lines.append('        self._queue.append(entry)')
lines.append('        logger.debug(')
lines.append('            "FactsWorker enqueue ts=%s player_uuid=%s queue_depth=%d",')
lines.append('            _ts_utc(),')
lines.append('            player_uuid,')
lines.append('            len(self._queue),')
lines.append('        )')
lines.append('        if not self._running:')
lines.append('            self.start()')
lines.append('')
lines.append('    @property')
lines.append('    def queue_depth(self) -> int:')
lines.append('        return len(self._queue)')
lines.append('')
lines.append('    def _run_loop(self) -> None:')
lines.append('        logger.info("FactsWorker run-loop started ts=%s", _ts_utc())')
lines.append('        while self._running:')
lines.append('            try:')
lines.append('                self._drain()')
lines.append('            except Exception as exc:')
lines.append('                logger.error("FactsWorker unhandled error in drain: %s", exc)')
lines.append('            time.sleep(0.1)')
lines.append('        logger.info("FactsWorker run-loop finished ts=%s", _ts_utc())')
lines.append('')
lines.append('    def _drain(self) -> None:')
lines.append('        try:')
lines.append('            entry = self._queue.popleft()')
lines.append('        except IndexError:')
lines.append('            return')
lines.append('')
lines.append('        player_uuid = str(entry["player_uuid"])')
lines.append('        chief_name = str(entry["chief_name"])')
lines.append('        player_message = str(entry["player_message"])')
lines.append('        retries = int(entry["retries"])')
lines.append('')
lines.append('        logger.debug(')
lines.append('            "FactsWorker processing ts=%s player_uuid=%s retry=%d",')
lines.append('            _ts_utc(),')
lines.append('            player_uuid,')
lines.append('            retries,')
lines.append('        )')
lines.append('')
lines.append('        try:')
lines.append('            self._analyze_facts(player_uuid, chief_name, player_message)')
lines.append('            logger.info(')
lines.append('                "FactsWorker OK ts=%s player_uuid=%s queue_depth=%d",')
lines.append('                _ts_utc(),')
lines.append('                player_uuid,')
lines.append('                len(self._queue),')
lines.append('            )')
lines.append('        except Exception as exc:')
lines.append('            retries += 1')
lines.append('            if retries < self._max_retries:')
lines.append('                entry["retries"] = retries')
lines.append('                self._queue.append(entry)')
lines.append('                logger.warning(')
lines.append('                    "FactsWorker retry ts=%s player_uuid=%s retries=%d/%d error=%s queue_depth=%d",')
lines.append('                    _ts_utc(),')
lines.append('                    player_uuid,')
lines.append('                    retries,')
lines.append('                    self._max_retries,')
lines.append('                    exc,')
lines.append('                    len(self._queue),')
lines.append('                )')
lines.append('            else:')
lines.append('                logger.error(')
lines.append('                    "FactsWorker discard ts=%s player_uuid=%s after %d retries error=%s",')
lines.append('                    _ts_utc(),')
lines.append('                    player_uuid,')
lines.append('                    retries,')
lines.append('                    exc,')
lines.append('                )')
lines.append('')
lines.append('    def _analyze_facts(self, player_uuid: str, chief_name: str, player_message: str) -> None:')
lines.append('        """Stub for the facts analysis pipeline (Paket C).')
lines.append('')
lines.append('        This method is intentionally left as a no-op for now.')
lines.append('        Future tickets will connect it to the qwen2.5:3b model and')
lines.append('        store extracted facts in the database.')
lines.append('        """')
lines.append('        logger.debug(')
lines.append('            "FactsWorker _analyze_facts stub ts=%s player_uuid=%s message_len=%d",')
lines.append('            _ts_utc(),')
lines.append('            player_uuid,')
lines.append('            len(player_message),')
lines.append('        )')
lines.append('        # TODO: implement in Paket C')

content = '\n'.join(lines) + '\n'
target = os.path.join('chief-ai-service', 'chief_ai_service', 'worker.py')
os.makedirs(os.path.dirname(target), exist_ok=True)
os.remove(target)  # remove corrupted file
with open(target, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Written {len(content)} bytes to {target}')