package de.ajsch.villagerai.model;

import java.util.UUID;
import org.jetbrains.annotations.Nullable;

public record AIRequest(
        String speakerId,
        String villageId,
        String villageName,
        String villageDescription,
        String villageAttributes,
        String villageBiome,
        int villagePopulationEstimate,
        String villageEventSummary,
        String displayName,
        String role,
        String personality,
        String speechTone,
        String behaviorHint,
        String greeting,
        String villagerProfession,
        String villagerType,
        String currentBiome,
        String worldName,
        boolean isDay,
        boolean isRaining,
        boolean isThundering,
        double currentHealth,
        double maxHealth,
        double healthRatio,
        boolean ateRecently,
        String tradeSummary,
        String confinementSummary,
        String authoritativeWorldFactsSummary,
        String recentConversation,
        String relationshipMemorySummary,
        String homePoi,
        String jobSitePoi,
        String potentialJobSitePoi,
        String meetingPointPoi,
        int villageReputationScore,
        String villageReputationSummary,
        int speakerReputationScore,
        String speakerReputationSummary,
        int combinedReputationScore,
        String combinedReputationSummary,
        int reputationScore,
        String reputationSummary,
        boolean villageHasChief,
                boolean villageMourning,
                String chiefLocation,
                String speakerStatus,
                String chiefNarrative,
                @Nullable ChiefAttributes chiefAttributes,
        UUID playerUuid,
        String playerMessage,
        boolean memoryEnabled,
        java.util.List<String> memoryTriggerFallbackPhrases) {
}