package de.ajsch.villagerai.model;

import java.util.UUID;

public record AIRequest(
        String chiefId,
        String villageId,
        String villageName,
        String villageDescription,
        String villageAttributes,
        String villageBiome,
        int villagePopulationEstimate,
        String villageEventSummary,
        String chiefName,
        String chiefRole,
        String chiefPersonality,
        String chiefTone,
        String chiefBehaviorHint,
        String chiefGreeting,
        String villagerProfession,
        String villagerType,
        String currentBiome,
        String worldName,
        boolean isDay,
        boolean isRaining,
        boolean isThundering,
        double currentHealth,
        double maxHealth,
        double healthRatio,
        boolean ateRecently,
        String tradeSummary,
        String confinementSummary,
        String authoritativeWorldFactsSummary,
        String recentConversation,
        String relationshipMemorySummary,
        String homePoi,
        String jobSitePoi,
        String potentialJobSitePoi,
        String meetingPointPoi,
        int villageReputationScore,
        String villageReputationSummary,
        int speakerReputationScore,
        String speakerReputationSummary,
        int combinedReputationScore,
        String combinedReputationSummary,
        int reputationScore,
        String reputationSummary,
        UUID playerUuid,
        String playerMessage) {
}